spring.cloud.stream:
  function:
    #    These are the functions that we register as the processing functions, these are semicolon (;) seperated values
    #    Multiple function example: fun1;fun2;fun3
    definition: sameSourceJoin
  bindings:
    sameSourceJoin-in-0:
      destination: cdc
    #      Defining an output topic for our stream function
    #    enrichProducts-out-0:
    #      destination: enriched-products

    #      Additional configurations
    #  kafka:
    #    bindings:
    #      numberProducer-out-0:
    #        producer:
    #          configuration:
    #            value:
    #              serializer: org.apache.kafka.common.serialization.LongSerializer
    binder:
      brokers:
        - localhost:9092